drop database if exists PtAppProject;
create database PtAppProject;
use PtAppProject;

drop table if exists member;
create table member(				# 회원정보
	memberCode int auto_increment,		# 회원코드(pk)
	ID varchar(20) not null unique,		# 회원ID
	PW varchar(30) not null,			# 회원비밀번호
	memberName varchar(10) not null,	# 회원이름
	height smallint not null,			# 키
	exHabit	tinyint not null,			# 운동습관
	gender char(1) not null,			# 성별
	birthDate varchar(20) not null,		# 생년월일
	contact	varchar(20) not null,		# 연락처
	accCategory tinyint not null,		# 회원분류코드
	primary key (memberCode)
);

drop table if exists food;
create table food(						# 음식
	foodCode int auto_increment,			# 음식코드(pk)
    foodName varchar(20) not null,			# 음식이름
    foodKcal smallint not null,				# 음식칼로리(대부분 100g당)
    primary key (foodCode)
);

drop table if exists exercise;
create table exercise (					# 운동
	exCode int auto_increment,				# 운동코드(pk)
    exName varchar(20) not null,			# 운동이름
	exKcal smallint not null,				# 운동소모칼로리(10분당)
    exIntensity tinyint not null,			# 운동강도(1~3)
    primary key (exCode)
);

drop table if exists weightrecord;
create table weightrecord(				# 몸무게기록표
	weightCode int auto_increment,			# 몸무게기록코드(pk)
	weight smallint not null,				# 몸무게측정결과
	measureTime datetime default now(),		# 몸무게측정시간
	memberCode int,							# 회원코드(fk)
    primary key (weightCode),
    foreign key (memberCode) references member(memberCode) on delete cascade
);

drop table if exists atefoodrecord;
create table atefoodrecord(				# 먹은음식기록표
	ateFoodCode int auto_increment,			# 먹은음식기록코드(pk)
    foodCode int,							# 음식코드(fk)
    ateTime datetime default now(),			# 먹은음식기록시간
    memberCode int,							# 회원코드(fk)
    primary key (ateFoodCode),
    foreign key (foodCode) references food(foodCode) on delete set null,
    foreign key (memberCode) references member(memberCode) on delete cascade
);

drop table if exists workoutrecord;
create table workoutrecord(				# 운동기록표
	workOutCode int auto_increment,			# 운동기록코드(pk)
    exCode int,								# 운동코드(fk)
    workOutTime datetime default now(),		# 운동기록시간
    memberCode int,							# 회원코드(fk)
    primary key (workOutCode),
    foreign key (exCode) references exercise(exCode) on delete set null,
    foreign key (memberCode) references member(memberCode) on delete cascade
);

drop table if exists message;
create table message (					# 쪽지
	messageCode int auto_increment,			# 쪽지코드(pk)
    sentMCode int,							# 보낸회원코드(fk)
    receivedMCode int,						# 받은회원코드(fk)
    msgTitle varchar(30),					# 쪽지제목
    msgContent text,						# 쪽지내용
	msgView	mediumint,						# 쪽지조회수
	msgDate datetime default now(),			# 쪽지전송시간
    replyContent text,						# 답장내용
    replyDate datetime default now(),		# 답장시간
    primary key (messageCode),
    foreign key (sentMCode) references member(memberCode) on delete set null,
    foreign key (receivedMCode) references member(memberCode) on delete set null
);

# member 테이블 샘플
INSERT INTO member (memberCode, ID, PW, memberName, height, exHabit, gender, birthDate, contact, accCategory) VALUES ('1', 'admin', 'admin', 'admin', 0, 0, 0, '', '', '1');
INSERT INTO member (memberCode, ID, PW, memberName, height, exHabit, gender, birthDate, contact, accCategory) VALUES ('2', 'member1', '1234', '아무개', '170', '1', 'M', '2000-01-01', '010-111-2222', '2');
INSERT INTO member (memberCode, ID, PW, memberName, height, exHabit, gender, birthDate, contact, accCategory) VALUES ('3', 'pt1', '4321', '김아무개', '173', '2', 'M', '2000-01-01', '010-111-2222', '3');
INSERT INTO member (memberCode, ID, PW, memberName, height, exHabit, gender, birthDate, contact, accCategory) VALUES ('4', 'member2', '1q1q', '이아무개', '167', '3', 'F', '2000-01-01', '010-111-2223', '2');
INSERT INTO member (memberCode, ID, PW, memberName, height, exHabit, gender, birthDate, contact, accCategory) VALUES ('5', 'pt2', '1111', '윤아무개', '170', '2', 'F', '2000-03-02', '010-111-2224', '3');

# food 테이블 샘플
INSERT INTO food (foodCode, foodName, foodKcal) VALUES ('1', '밥', '100');
INSERT INTO food (foodCode, foodName, foodKcal) VALUES ('2', '김밥', '150');
INSERT INTO food (foodCode, foodName, foodKcal) VALUES ('3', '불고기', '200');
INSERT INTO food (foodCode, foodName, foodKcal) VALUES ('4', '된장찌개', '200');
INSERT INTO food (foodCode, foodName, foodKcal) VALUES ('5', '떡볶이', '250');

# exercise 테이블 샘플
INSERT INTO exercise (exCode, exName, exKcal, exIntensity) VALUES ('1', '걷기', '30', '1');
INSERT INTO exercise (exCode, exName, exKcal, exIntensity) VALUES ('2', '조깅', '60', '2');
INSERT INTO exercise (exCode, exName, exKcal, exIntensity) VALUES ('3', '수영', '60', '1');
INSERT INTO exercise (exCode, exName, exKcal, exIntensity) VALUES ('4', '자전거타기', '40', '2');
INSERT INTO exercise (exCode, exName, exKcal, exIntensity) VALUES ('5', '계단오르내리기', '80', '3');

# weightrecord 테이블 샘플
INSERT INTO weightrecord (weightCode, weight, measureTime, memberCode) VALUES ('1', '100', '2024-07-02 08:40:15', '1');
INSERT INTO weightrecord (weightCode, weight, measureTime, memberCode) VALUES ('2', '101', '2024-07-02 16:40:50', '1');
INSERT INTO weightrecord (weightCode, weight, measureTime, memberCode) VALUES ('3', '80', '2024-07-02 08:45:42', '2');
INSERT INTO weightrecord (weightCode, weight, measureTime, memberCode) VALUES ('4', '81', '2024-07-02 17:50:11', '2');
INSERT INTO weightrecord (weightCode, weight, measureTime, memberCode) VALUES ('5', '70', '2024-07-02 08:40:12', '3');

# atefoodrecord 테이블 샘플
INSERT INTO atefoodrecord (ateFoodCode, foodCode, ateTime, memberCode) VALUES ('1', '1', '2024-07-02 08:40:15', '1');
INSERT INTO atefoodrecord (ateFoodCode, foodCode, ateTime, memberCode) VALUES ('2', '2', '2024-07-02 16:40:50', '1');
INSERT INTO atefoodrecord (ateFoodCode, foodCode, ateTime, memberCode) VALUES ('3', '1', '2024-07-02 08:45:42', '2');
INSERT INTO atefoodrecord (ateFoodCode, foodCode, ateTime, memberCode) VALUES ('4', '1', '2024-07-02 17:50:11', '2');
INSERT INTO atefoodrecord (ateFoodCode, foodCode, ateTime, memberCode) VALUES ('5', '1', '2024-07-02 08:40:12', '3');

# workoutrecord 테이블 샘플
INSERT INTO workoutrecord (workOutCode, exCode, workOutTime, memberCode) VALUES ('1', '1', '2024-07-02 08:40:15', '1');
INSERT INTO workoutrecord (workOutCode, exCode, workOutTime, memberCode) VALUES ('2', '3', '2024-07-02 16:40:50', '1');
INSERT INTO workoutrecord (workOutCode, exCode, workOutTime, memberCode) VALUES ('3', '2', '2024-07-02 08:45:42', '2');
INSERT INTO workoutrecord (workOutCode, exCode, workOutTime, memberCode) VALUES ('4', '4', '2024-07-02 17:50:11', '3');
INSERT INTO workoutrecord (workOutCode, exCode, workOutTime, memberCode) VALUES ('5', '5', '2024-07-02 08:40:12', '3');

# message 테이블 샘플
INSERT INTO message (messageCode, sentMCode, receivedMCode, msgTitle, msgContent, msgView, msgDate, replyContent, replyDate) VALUES ('1', '2', '3', '안녕하세요', '내용1', '1', '2024-07-02 08:40:15', '답장1', '2024-07-02 16:40:50');
INSERT INTO message (messageCode, sentMCode, receivedMCode, msgTitle, msgContent, msgView, msgDate, replyContent, replyDate) VALUES ('2', '2', '3', '안녕하세요', '내용2', '0', '2024-07-02 16:40:50', null, null);
INSERT INTO message (messageCode, sentMCode, receivedMCode, msgTitle, msgContent, msgView, msgDate, replyContent, replyDate) VALUES ('3', '4', '3', '안녕하세요', '내용3', '1', '2024-07-02 08:45:42', '답장3', '2024-07-02 17:20:11');
INSERT INTO message (messageCode, sentMCode, receivedMCode, msgTitle, msgContent, msgView, msgDate, replyContent, replyDate) VALUES ('4', '4', '5', '안녕하세요', '내용4', '1', '2024-07-02 17:50:11', '답장4', '2024-07-02 17:50:21');
INSERT INTO message (messageCode, sentMCode, receivedMCode, msgTitle, msgContent, msgView, msgDate, replyContent, replyDate) VALUES ('5', '4', '5', '안녕하세요', '내용5', '0', '2024-07-02 08:40:12', null, null);

#food DB
insert into food(foodName,foodKcal) values (' 사과 ',95);
insert into food(foodName,foodKcal) values (' 바나나 ',105);
insert into food(foodName,foodKcal) values (' 오렌지 ',62);
insert into food(foodName,foodKcal) values (' 포도 ',69);
insert into food(foodName,foodKcal) values (' 딸기 ',32);
insert into food(foodName,foodKcal) values (' 수박 ',30);
insert into food(foodName,foodKcal) values (' 블루베리 ',57);
insert into food(foodName,foodKcal) values (' 망고 ',150);
insert into food(foodName,foodKcal) values (' 파인애플 ',50);
insert into food(foodName,foodKcal) values (' 체리 ',50);
insert into food(foodName,foodKcal) values (' 시금치 ',23);
insert into food(foodName,foodKcal) values (' 브로콜리 ',34);
insert into food(foodName,foodKcal) values (' 당근 ',41);
insert into food(foodName,foodKcal) values (' 토마토 ',22);
insert into food(foodName,foodKcal) values (' 양배추 ',25);
insert into food(foodName,foodKcal) values (' 오이 ',16);
insert into food(foodName,foodKcal) values (' 감자 ',110);
insert into food(foodName,foodKcal) values (' 고구마 ',112);
insert into food(foodName,foodKcal) values (' 호박 ',26);
insert into food(foodName,foodKcal) values (' 콜리플라워 ',25);
insert into food(foodName,foodKcal) values (' 닭 가슴살 ',165);
insert into food(foodName,foodKcal) values (' 소고기 ',250);
insert into food(foodName,foodKcal) values (' 돼지고기 ',242);
insert into food(foodName,foodKcal) values (' 연어 ',206);
insert into food(foodName,foodKcal) values (' 참치 ',184);
insert into food(foodName,foodKcal) values (' 새우 ',99);
insert into food(foodName,foodKcal) values (' 오징어 ',92);
insert into food(foodName,foodKcal) values (' 대구 ',105);
insert into food(foodName,foodKcal) values (' 고등어 ',205);
insert into food(foodName,foodKcal) values (' 가자미 ',117);
insert into food(foodName,foodKcal) values (' 쌀밥 ',206);
insert into food(foodName,foodKcal) values (' 현미밥 ',215);
insert into food(foodName,foodKcal) values (' 식빵 ',70);
insert into food(foodName,foodKcal) values (' 크로와상 ',231);
insert into food(foodName,foodKcal) values (' 베이글 ',245);
insert into food(foodName,foodKcal) values (' 스파게티 ',158);
insert into food(foodName,foodKcal) values (' 라면 ',380);
insert into food(foodName,foodKcal) values (' 피자 ',285);
insert into food(foodName,foodKcal) values (' 햄버거 ',354);
insert into food(foodName,foodKcal) values (' 핫도그 ',290);
insert into food(foodName,foodKcal) values (' 우유 ',149);
insert into food(foodName,foodKcal) values (' 두유 ',131);
insert into food(foodName,foodKcal) values (' 요거트 ',149);
insert into food(foodName,foodKcal) values (' 치즈 ',402);
insert into food(foodName,foodKcal) values (' 달걀 ',72);
insert into food(foodName,foodKcal) values (' 아몬드 ',575);
insert into food(foodName,foodKcal) values (' 땅콩 ',567);
insert into food(foodName,foodKcal) values (' 호두 ',654);
insert into food(foodName,foodKcal) values (' 캐슈넛 ',553);
insert into food(foodName,foodKcal) values (' 해바라기씨 ',584);
insert into food(foodName,foodKcal) values (' 초콜릿 ',535);
insert into food(foodName,foodKcal) values (' 사탕 ',394);
insert into food(foodName,foodKcal) values (' 아이스크림 ',207);
insert into food(foodName,foodKcal) values (' 쿠키 ',78);
insert into food(foodName,foodKcal) values (' 케이크 ',257);
insert into food(foodName,foodKcal) values (' 도넛 ',195);
insert into food(foodName,foodKcal) values (' 머핀 ',377);
insert into food(foodName,foodKcal) values (' 파이 ',237);
insert into food(foodName,foodKcal) values (' 젤리 ',343);
insert into food(foodName,foodKcal) values (' 팝콘 ',375);
insert into food(foodName,foodKcal) values (' 감자튀김 ',312);
insert into food(foodName,foodKcal) values (' 치킨너겟 ',296);
insert into food(foodName,foodKcal) values (' 소시지 ',301);
insert into food(foodName,foodKcal) values (' 베이컨 ',541);
insert into food(foodName,foodKcal) values (' 햄 ',145);
insert into food(foodName,foodKcal) values (' 살라미 ',336);
insert into food(foodName,foodKcal) values (' 훈제 연어 ',117);
insert into food(foodName,foodKcal) values (' 참치 캔 ',116);
insert into food(foodName,foodKcal) values (' 스팸 ',315);
insert into food(foodName,foodKcal) values (' 핫윙 ',203);
insert into food(foodName,foodKcal) values (' 그린 샐러드 ',17);
insert into food(foodName,foodKcal) values (' 시저 샐러드 ',190);
insert into food(foodName,foodKcal) values (' 콥 샐러드 ',171);
insert into food(foodName,foodKcal) values (' 연어 샐러드 ',142);
insert into food(foodName,foodKcal) values (' 과일 샐러드 ',50);
insert into food(foodName,foodKcal) values (' 토마토 수프 ',74);
insert into food(foodName,foodKcal) values (' 치킨 누들 수프 ',75);
insert into food(foodName,foodKcal) values (' 야채 수프 ',67);
insert into food(foodName,foodKcal) values (' 클램 차우더 ',154);
insert into food(foodName,foodKcal) values (' 미소 수프 ',84);
insert into food(foodName,foodKcal) values (' 김밥 ',230);
insert into food(foodName,foodKcal) values (' 초밥 ',40);
insert into food(foodName,foodKcal) values (' 떡볶이 ',250);
insert into food(foodName,foodKcal) values (' 잡채 ',150);
insert into food(foodName,foodKcal) values (' 불고기 ',190);
insert into food(foodName,foodKcal) values (' 김치 ',15);
insert into food(foodName,foodKcal) values (' 된장국 ',80);
insert into food(foodName,foodKcal) values (' 갈비탕 ',130);
insert into food(foodName,foodKcal) values (' 비빔밥 ',576);
insert into food(foodName,foodKcal) values (' 찜닭 ',160);
insert into food(foodName,foodKcal) values (' 파스타 ',158);
insert into food(foodName,foodKcal) values (' 라자냐 ',135);
insert into food(foodName,foodKcal) values (' 카르보나라 ',220);
insert into food(foodName,foodKcal) values (' 페스토 파스타 ',290);
insert into food(foodName,foodKcal) values (' 미트볼 ',230);
insert into food(foodName,foodKcal) values (' 브루스케타 ',150);
insert into food(foodName,foodKcal) values (' 티라미수 ',245);
insert into food(foodName,foodKcal) values (' 판나코타 ',210);
insert into food(foodName,foodKcal) values (' 리조또 ',138);
insert into food(foodName,foodKcal) values (' 카프레제 ',150);
insert into food(foodName,foodKcal) values (' 배 ',102);
insert into food(foodName,foodKcal) values (' 자몽 ',52);
insert into food(foodName,foodKcal) values (' 복숭아 ',59);
insert into food(foodName,foodKcal) values (' 네이블 오렌지 ',69);
insert into food(foodName,foodKcal) values (' 라즈베리 ',52);
insert into food(foodName,foodKcal) values (' 블랙베리 ',43);
insert into food(foodName,foodKcal) values (' 석류 ',234);
insert into food(foodName,foodKcal) values (' 레몬 ',17);
insert into food(foodName,foodKcal) values (' 라임 ',20);
insert into food(foodName,foodKcal) values (' 키위 ',42);
insert into food(foodName,foodKcal) values (' 아보카도 ',234);
insert into food(foodName,foodKcal) values (' 아스파라거스 ',20);
insert into food(foodName,foodKcal) values (' 비트 ',43);
insert into food(foodName,foodKcal) values (' 브뤼셀 스프라우트 ',43);
insert into food(foodName,foodKcal) values (' 버섯 ',22);
insert into food(foodName,foodKcal) values (' 파슬리 ',36);
insert into food(foodName,foodKcal) values (' 콜라드 그린 ',32);
insert into food(foodName,foodKcal) values (' 근대 ',19);
insert into food(foodName,foodKcal) values (' 피망 ',31);
insert into food(foodName,foodKcal) values (' 가지 ',25);
insert into food(foodName,foodKcal) values (' 터키 ',189);
insert into food(foodName,foodKcal) values (' 양고기 ',294);
insert into food(foodName,foodKcal) values (' 오리 고기 ',337);
insert into food(foodName,foodKcal) values (' 게 ',97);
insert into food(foodName,foodKcal) values (' 랍스터 ',89);
insert into food(foodName,foodKcal) values (' 조개 ',74);
insert into food(foodName,foodKcal) values (' 홍합 ',86);
insert into food(foodName,foodKcal) values (' 스캘럽 ',111);
insert into food(foodName,foodKcal) values (' 굴 ',68);
insert into food(foodName,foodKcal) values (' 문어 ',82);
insert into food(foodName,foodKcal) values (' 퀴노아 ',120);
insert into food(foodName,foodKcal) values (' 보리 ',123);
insert into food(foodName,foodKcal) values (' 오트밀 ',71);
insert into food(foodName,foodKcal) values (' 메밀 ',92);
insert into food(foodName,foodKcal) values (' 팥 ',127);
insert into food(foodName,foodKcal) values (' 검은콩 ',132);
insert into food(foodName,foodKcal) values (' 병아리콩 ',164);
insert into food(foodName,foodKcal) values (' 렌틸콩 ',116);
insert into food(foodName,foodKcal) values (' 피스타치오 ',562);
insert into food(foodName,foodKcal) values (' 헤이즐넛 ',628);
insert into food(foodName,foodKcal) values (' 그릭 요거트 ',59);
insert into food(foodName,foodKcal) values (' 크림 치즈 ',342);
insert into food(foodName,foodKcal) values (' 모차렐라 치즈 ',280);
insert into food(foodName,foodKcal) values (' 리코타 치즈 ',174);
insert into food(foodName,foodKcal) values (' 파마산 치즈 ',431);
insert into food(foodName,foodKcal) values (' 코티지 치즈 ',98);
insert into food(foodName,foodKcal) values (' 사워크림 ',214);
insert into food(foodName,foodKcal) values (' 버터 ',717);
insert into food(foodName,foodKcal) values (' 마가린 ',717);
insert into food(foodName,foodKcal) values (' 크림 ',345);
insert into food(foodName,foodKcal) values (' 브라운 설탕 ',380);
insert into food(foodName,foodKcal) values (' 꿀 ',304);
insert into food(foodName,foodKcal) values (' 메이플 시럽 ',260);
insert into food(foodName,foodKcal) values (' 잼 ',250);
insert into food(foodName,foodKcal) values (' 마멀레이드 ',246);
insert into food(foodName,foodKcal) values (' 땅콩 버터 ',588);
insert into food(foodName,foodKcal) values (' 아몬드 버터 ',614);
insert into food(foodName,foodKcal) values (' 타히니 ',595);
insert into food(foodName,foodKcal) values (' 올리브 오일 ',884);
insert into food(foodName,foodKcal) values (' 코코넛 오일 ',892);
insert into food(foodName,foodKcal) values (' 퀘사디아 ',326);
insert into food(foodName,foodKcal) values (' 타코 ',226);
insert into food(foodName,foodKcal) values (' 브리또 ',320);
insert into food(foodName,foodKcal) values (' 엔칠라다 ',220);
insert into food(foodName,foodKcal) values (' 나초 ',340);
insert into food(foodName,foodKcal) values (' 또띠야 ',159);
insert into food(foodName,foodKcal) values (' 구아카몰 ',155);
insert into food(foodName,foodKcal) values (' 살사 ',36);
insert into food(foodName,foodKcal) values (' 초리조 ',455);
insert into food(foodName,foodKcal) values (' 타말레 ',285);
insert into food(foodName,foodKcal) values (' 크림 소스 ',196);
insert into food(foodName,foodKcal) values (' 바베큐 소스 ',100);
insert into food(foodName,foodKcal) values (' 칠리 소스 ',56);
insert into food(foodName,foodKcal) values (' 간장 ',53);
insert into food(foodName,foodKcal) values (' 타르타르 소스 ',220);
insert into food(foodName,foodKcal) values (' 마요네즈 ',680);
insert into food(foodName,foodKcal) values (' 케첩 ',112);
insert into food(foodName,foodKcal) values (' 머스타드 ',66);
insert into food(foodName,foodKcal) values (' 핫 소스 ',15);
insert into food(foodName,foodKcal) values (' 피클 ',12);
insert into food(foodName,foodKcal) values (' 무스 ',196);
insert into food(foodName,foodKcal) values (' 크렘브륄레 ',248);
insert into food(foodName,foodKcal) values (' 에클레어 ',262);
insert into food(foodName,foodKcal) values (' 슈크림 ',190);
insert into food(foodName,foodKcal) values (' 마카롱 ',70);
insert into food(foodName,foodKcal) values (' 팥빙수 ',90);
insert into food(foodName,foodKcal) values (' 붕어빵 ',112);
insert into food(foodName,foodKcal) values (' 떡 ',210);
insert into food(foodName,foodKcal) values (' 단팥빵 ',233);
insert into food(foodName,foodKcal) values (' 호두과자 ',60);
insert into food(foodName,foodKcal) values (' 훈제 치킨 ',189);
insert into food(foodName,foodKcal) values (' 칠리 ',151);
insert into food(foodName,foodKcal) values (' 스튜 ',150);
insert into food(foodName,foodKcal) values (' 팔라펠 ',333);
insert into food(foodName,foodKcal) values (' 허머스 ',166);
insert into food(foodName,foodKcal) values (' 타블레 ',119);
insert into food(foodName,foodKcal) values (' 케밥 ',200);
insert into food(foodName,foodKcal) values (' 샤와르마 ',150);
insert into food(foodName,foodKcal) values (' 플랫브레드 ',270);
insert into food(foodName,foodKcal) values (' 피칸 ',691);
insert into food(foodName,foodKcal) values (' 마카다미아 ',718);
insert into food(foodName,foodKcal) values (' 바질 페스토 ',303);
insert into food(foodName,foodKcal) values (' 쌀국수 ',108);
insert into food(foodName,foodKcal) values (' 라이스페이퍼 ',20);
insert into food(foodName,foodKcal) values (' 가지볶음 ',82);
insert into food(foodName,foodKcal) values (' 마파두부 ',150);
insert into food(foodName,foodKcal) values (' 짜장면 ',650);
insert into food(foodName,foodKcal) values (' 짬뽕 ',450);
insert into food(foodName,foodKcal) values (' 팔보채 ',150);
insert into food(foodName,foodKcal) values (' 꽃빵 ',54);
insert into food(foodName,foodKcal) values (' 동파육 ',400);
insert into food(foodName,foodKcal) values (' 딤섬 ',50);
insert into food(foodName,foodKcal) values (' 우동 ',130);
insert into food(foodName,foodKcal) values (' 소고기 전골 ',100);
insert into food(foodName,foodKcal) values (' 낙지볶음 ',120);
insert into food(foodName,foodKcal) values (' 삼계탕 ',800);
insert into food(foodName,foodKcal) values (' 추어탕 ',400);
insert into food(foodName,foodKcal) values (' 해물파전 ',180);
insert into food(foodName,foodKcal) values (' 감자전 ',150);
insert into food(foodName,foodKcal) values (' 만두 ',45);
insert into food(foodName,foodKcal) values (' 갈비찜 ',250);
insert into food(foodName,foodKcal) values (' 떡국 ',400);
insert into food(foodName,foodKcal) values (' 설렁탕 ',550);
insert into food(foodName,foodKcal) values (' 곰탕 ',600);
insert into food(foodName,foodKcal) values (' 육개장 ',500);
insert into food(foodName,foodKcal) values (' 순대 ',150);
insert into food(foodName,foodKcal) values (' 족발 ',250);
insert into food(foodName,foodKcal) values (' 보쌈 ',250);
insert into food(foodName,foodKcal) values (' 매운탕 ',200);
insert into food(foodName,foodKcal) values (' 감자탕 ',600);
insert into food(foodName,foodKcal) values (' 김치찌개 ',400);
insert into food(foodName,foodKcal) values (' 된장찌개 ',350);
insert into food(foodName,foodKcal) values (' 순두부찌개 ',300);
insert into food(foodName,foodKcal) values (' 해물탕 ',250);
insert into food(foodName,foodKcal) values (' 칼국수 ',400);
insert into food(foodName,foodKcal) values (' 비지찌개 ',350);
insert into food(foodName,foodKcal) values (' 콩나물국밥 ',350);
insert into food(foodName,foodKcal) values (' 수제비 ',400);
insert into food(foodName,foodKcal) values (' 라볶이 ',400);
insert into food(foodName,foodKcal) values (' 치즈돈까스 ',600);
insert into food(foodName,foodKcal) values (' 카레라이스 ',600);
insert into food(foodName,foodKcal) values (' 오므라이스 ',600);
insert into food(foodName,foodKcal) values (' 치킨카레 ',550);
insert into food(foodName,foodKcal) values (' 소고기덮밥 ',650);
insert into food(foodName,foodKcal) values (' 장어덮밥 ',700);
insert into food(foodName,foodKcal) values (' 참치마요덮밥 ',600);
insert into food(foodName,foodKcal) values (' 연어덮밥 ',550);
insert into food(foodName,foodKcal) values (' 고등어구이 ',200);
insert into food(foodName,foodKcal) values (' 갈치구이 ',180);
insert into food(foodName,foodKcal) values (' 곱창구이 ',200);
insert into food(foodName,foodKcal) values (' 막창구이 ',250);
insert into food(foodName,foodKcal) values (' 대창구이 ',300);
insert into food(foodName,foodKcal) values (' 닭갈비 ',200);
insert into food(foodName,foodKcal) values (' 닭강정 ',300);
insert into food(foodName,foodKcal) values (' 닭똥집 ',150);
insert into food(foodName,foodKcal) values (' 닭발 ',250);
insert into food(foodName,foodKcal) values (' 양념치킨 ',290);
insert into food(foodName,foodKcal) values (' 후라이드치킨 ',250);
insert into food(foodName,foodKcal) values (' 간장치킨 ',270);
insert into food(foodName,foodKcal) values (' 조개구이 ',150);
insert into food(foodName,foodKcal) values (' 대하구이 ',120);
insert into food(foodName,foodKcal) values (' 고등어조림 ',220);
insert into food(foodName,foodKcal) values (' 갈치조림 ',200);
insert into food(foodName,foodKcal) values (' 동태조림 ',150);
insert into food(foodName,foodKcal) values (' 낙지볶음밥 ',600);
insert into food(foodName,foodKcal) values (' 제육볶음밥 ',650);
insert into food(foodName,foodKcal) values (' 돼지불백 ',250);
insert into food(foodName,foodKcal) values (' 오징어볶음 ',180);
insert into food(foodName,foodKcal) values (' 갈치조림밥 ',550);
insert into food(foodName,foodKcal) values (' 매콤치킨 ',290);
insert into food(foodName,foodKcal) values (' 해물찜 ',150);
insert into food(foodName,foodKcal) values (' 갈비찜 ',750);
insert into food(foodName,foodKcal) values (' 묵은지김치찜 ',180);
insert into food(foodName,foodKcal) values (' 감자채볶음 ',120);
insert into food(foodName,foodKcal) values (' 연근조림 ',150);
insert into food(foodName,foodKcal) values (' 오이무침 ',50);
insert into food(foodName,foodKcal) values (' 무생채 ',40);
insert into food(foodName,foodKcal) values (' 김말이 ',250);
insert into food(foodName,foodKcal) values (' 도토리묵 ',45);
insert into food(foodName,foodKcal) values (' 메밀전병 ',180);
insert into food(foodName,foodKcal) values (' 콩나물무침 ',60);
insert into food(foodName,foodKcal) values (' 두부조림 ',100);
insert into food(foodName,foodKcal) values (' 된장무침 ',80);
insert into food(foodName,foodKcal) values (' 무조림 ',70);
insert into food(foodName,foodKcal) values (' 호박전 ',150);
insert into food(foodName,foodKcal) values (' 참치회 ',150);
insert into food(foodName,foodKcal) values (' 연어회 ',200);
insert into food(foodName,foodKcal) values (' 우럭회 ',110);
insert into food(foodName,foodKcal) values (' 광어회 ',120);
insert into food(foodName,foodKcal) values (' 문어숙회 ',82);
insert into food(foodName,foodKcal) values (' 해삼 ',60);
insert into food(foodName,foodKcal) values (' 멍게 ',70);
insert into food(foodName,foodKcal) values (' 꽃게탕 ',300);
insert into food(foodName,foodKcal) values (' 새우튀김 ',250);
insert into food(foodName,foodKcal) values (' 오징어튀김 ',220);
insert into food(foodName,foodKcal) values (' 감자튀김 ',310);
insert into food(foodName,foodKcal) values (' 고구마튀김 ',290);
insert into food(foodName,foodKcal) values (' 고로케 ',250);
insert into food(foodName,foodKcal) values (' 도넛 ',452);
insert into food(foodName,foodKcal) values (' 햄버거 ',354);
insert into food(foodName,foodKcal) values (' 치즈버거 ',303);
insert into food(foodName,foodKcal) values (' 베이컨 ',541);
insert into food(foodName,foodKcal) values (' 스테이크 ',271);
insert into food(foodName,foodKcal) values (' 립스테이크 ',291);
insert into food(foodName,foodKcal) values (' 불고기 ',196);
insert into food(foodName,foodKcal) values (' 샤브샤브 ',80);
insert into food(foodName,foodKcal) values (' 양념 갈비 ',288);
insert into food(foodName,foodKcal) values (' 곱창전골 ',103);
insert into food(foodName,foodKcal) values (' 어묵 ',156);
insert into food(foodName,foodKcal) values (' 비빔밥 ',570);
insert into food(foodName,foodKcal) values (' 육회비빔밥 ',650);
insert into food(foodName,foodKcal) values (' 순두부백반 ',400);
insert into food(foodName,foodKcal) values (' 알밥 ',530);
insert into food(foodName,foodKcal) values (' 쌈밥 ',450);
insert into food(foodName,foodKcal) values (' 김치볶음밥 ',560);
insert into food(foodName,foodKcal) values (' 계란볶음밥 ',500);
insert into food(foodName,foodKcal) values (' 참치마요김밥 ',360);
insert into food(foodName,foodKcal) values (' 새우김밥 ',300);
insert into food(foodName,foodKcal) values (' 불고기김밥 ',400);
insert into food(foodName,foodKcal) values (' 오징어덮밥 ',480);
insert into food(foodName,foodKcal) values (' 삼치구이 ',200);
insert into food(foodName,foodKcal) values (' 조기구이 ',220);
insert into food(foodName,foodKcal) values (' 연어스테이크 ',208);
insert into food(foodName,foodKcal) values (' 고등어조림 ',178);
insert into food(foodName,foodKcal) values (' 꽁치조림 ',203);
insert into food(foodName,foodKcal) values (' 굴비구이 ',220);
insert into food(foodName,foodKcal) values (' 명태구이 ',220);
insert into food(foodName,foodKcal) values (' 송어구이 ',190);
insert into food(foodName,foodKcal) values (' 홍어회 ',70);
insert into food(foodName,foodKcal) values (' 매운 갈비찜 ',800);
insert into food(foodName,foodKcal) values (' 보쌈정식 ',600);
insert into food(foodName,foodKcal) values (' 제육볶음 ',212);
insert into food(foodName,foodKcal) values (' 오리불고기 ',240);
insert into food(foodName,foodKcal) values (' 안심스테이크 ',194);
insert into food(foodName,foodKcal) values (' 토시살 스테이크 ',217);
insert into food(foodName,foodKcal) values (' 양갈비 ',282);
insert into food(foodName,foodKcal) values (' 육전 ',280);
insert into food(foodName,foodKcal) values (' 갈매기살 ',280);
insert into food(foodName,foodKcal) values (' 차돌박이 ',350);
insert into food(foodName,foodKcal) values (' 카프레제 ',250);
insert into food(foodName,foodKcal) values (' 시저 샐러드 ',190);
insert into food(foodName,foodKcal) values (' 리코타 샐러드 ',180);
insert into food(foodName,foodKcal) values (' 아보카도 샐러드 ',160);
insert into food(foodName,foodKcal) values (' 그리스 샐러드 ',100);
insert into food(foodName,foodKcal) values (' 닭가슴살 샐러드 ',120);
insert into food(foodName,foodKcal) values (' 연어 샐러드 ',140);
insert into food(foodName,foodKcal) values (' 콥 샐러드 ',160);
insert into food(foodName,foodKcal) values (' 퀴노아 샐러드 ',120);
insert into food(foodName,foodKcal) values (' 새우 샐러드 ',120);
insert into food(foodName,foodKcal) values (' 가지볶음 ',82);
insert into food(foodName,foodKcal) values (' 우엉조림 ',200);
insert into food(foodName,foodKcal) values (' 모둠전 ',250);
insert into food(foodName,foodKcal) values (' 미트로프 ',200);
insert into food(foodName,foodKcal) values (' 프렌치 토스트 ',226);
insert into food(foodName,foodKcal) values (' 팬케이크 ',86);
insert into food(foodName,foodKcal) values (' 와플 ',195);
insert into food(foodName,foodKcal) values (' 크레페 ',225);
insert into food(foodName,foodKcal) values (' 에그 베네딕트 ',226);
insert into food(foodName,foodKcal) values (' 치킨앤와플 ',460);
insert into food(foodName,foodKcal) values (' 버팔로윙 ',250);
insert into food(foodName,foodKcal) values (' 허니버터치킨 ',290);
insert into food(foodName,foodKcal) values (' 마늘간장치킨 ',270);
insert into food(foodName,foodKcal) values (' 프라이드 치킨 윙 ',99);
insert into food(foodName,foodKcal) values (' 테리야키 치킨 ',150);
insert into food(foodName,foodKcal) values (' 바비큐 립 ',290);
insert into food(foodName,foodKcal) values (' 포크 립 ',300);
insert into food(foodName,foodKcal) values (' 베이비 백 립 ',320);
insert into food(foodName,foodKcal) values (' 햄 스테이크 ',230);
insert into food(foodName,foodKcal) values (' 코리안 바비큐 ',200);
insert into food(foodName,foodKcal) values (' 크로와상 ',406);
insert into food(foodName,foodKcal) values (' 베이글 ',289);
insert into food(foodName,foodKcal) values (' 브리오슈 ',339);
insert into food(foodName,foodKcal) values (' 치아바타 ',262);
insert into food(foodName,foodKcal) values (' 포카치아 ',249);
insert into food(foodName,foodKcal) values (' 바게트 ',250);
insert into food(foodName,foodKcal) values (' 사워도우 ',270);
insert into food(foodName,foodKcal) values (' 멀티그레인 빵 ',265);
insert into food(foodName,foodKcal) values (' 라이 브레드 ',259);
insert into food(foodName,foodKcal) values (' 잉글리시 머핀 ',134);
insert into food(foodName,foodKcal) values (' 페스토 파스타 ',370);
insert into food(foodName,foodKcal) values (' 알프레도 파스타 ',460);
insert into food(foodName,foodKcal) values (' 볼로네즈 파스타 ',380);
insert into food(foodName,foodKcal) values (' 해물 파스타 ',320);
insert into food(foodName,foodKcal) values (' 까르보나라 파스타 ',420);
insert into food(foodName,foodKcal) values (' 라자냐 ',336);
insert into food(foodName,foodKcal) values (' 스파게티 ',158);
insert into food(foodName,foodKcal) values (' 펜네 ',126);
insert into food(foodName,foodKcal) values (' 파파델레 ',131);
insert into food(foodName,foodKcal) values (' 링귀니 ',158);
insert into food(foodName,foodKcal) values (' 치즈 플레이트 ',400);
insert into food(foodName,foodKcal) values (' 푸아그라 ',462);
insert into food(foodName,foodKcal) values (' 트러플 오일 ',884);
insert into food(foodName,foodKcal) values (' 오믈렛 ',154);
insert into food(foodName,foodKcal) values (' 데블드 에그 ',64);
insert into food(foodName,foodKcal) values (' 스크램블드 에그 ',148);
insert into food(foodName,foodKcal) values (' 베이컨 에그 샌드위치 ',356);
insert into food(foodName,foodKcal) values (' 에그 맥머핀 ',290);
insert into food(foodName,foodKcal) values (' BLT 샌드위치 ',352);
insert into food(foodName,foodKcal) values (' 클럽 샌드위치 ',450);
insert into food(foodName,foodKcal) values ('초밥 ',40-60);
insert into food(foodName,foodKcal) values ('캘리포니아 롤 ',30-50);
insert into food(foodName,foodKcal) values ('회덮밥 ',480);
insert into food(foodName,foodKcal) values ('텐동 ',650);
insert into food(foodName,foodKcal) values ('카레우동 ',500);
insert into food(foodName,foodKcal) values ('메밀소바 ',300);
insert into food(foodName,foodKcal) values ('돈카츠 ',600);
insert into food(foodName,foodKcal) values ('오야코동 ',550);
insert into food(foodName,foodKcal) values ('규동 ',650);
insert into food(foodName,foodKcal) values ('야키소바 ',500);
insert into food(foodName,foodKcal) values ('다코야키 ',40);
insert into food(foodName,foodKcal) values ('오코노미야키 ',400);
insert into food(foodName,foodKcal) values ('튀김우동 ',450);
insert into food(foodName,foodKcal) values ('야키토리 ',150);
insert into food(foodName,foodKcal) values ('에비튀김 ',100);
insert into food(foodName,foodKcal) values ('가츠동 ',650);
insert into food(foodName,foodKcal) values ('라멘 ',500-600);
insert into food(foodName,foodKcal) values ('스시 ',50-60);
insert into food(foodName,foodKcal) values ('아게다시 도후 ',150);
insert into food(foodName,foodKcal) values ('나베 ',400);
insert into food(foodName,foodKcal) values ('타마고야키 ',150);
insert into food(foodName,foodKcal) values ('치킨 가라아게 ',290);
insert into food(foodName,foodKcal) values ('모치 ',50-60);
insert into food(foodName,foodKcal) values ('도라야끼 ',150);
insert into food(foodName,foodKcal) values ('팥빙수 ',250);
insert into food(foodName,foodKcal) values ('단팥죽 ',320);
insert into food(foodName,foodKcal) values ('고구마 스틱 ',150);
insert into food(foodName,foodKcal) values ('인절미 ',220);
insert into food(foodName,foodKcal) values ('약식 ',240);
insert into food(foodName,foodKcal) values ('찹쌀떡 ',160);
insert into food(foodName,foodKcal) values ('송편 ',60-80);
insert into food(foodName,foodKcal) values ('붕어빵 ',120);
insert into food(foodName,foodKcal) values ('호떡 ',230);
insert into food(foodName,foodKcal) values ('계란빵 ',150);
insert into food(foodName,foodKcal) values ('떡꼬치 ',180);
insert into food(foodName,foodKcal) values ('오뎅 ',60);
insert into food(foodName,foodKcal) values ('순대국 ',350);
insert into food(foodName,foodKcal) values ('수육 ',250);
insert into food(foodName,foodKcal) values ('도가니탕 ',350);
insert into food(foodName,foodKcal) values ('곰탕 ',550);
insert into food(foodName,foodKcal) values ('설렁탕 ',550);
insert into food(foodName,foodKcal) values ('삼계탕 ',800);
insert into food(foodName,foodKcal) values ('닭볶음탕 ',450);
insert into food(foodName,foodKcal) values ('해물탕 ',250);
insert into food(foodName,foodKcal) values ('김치찌개 ',400);
insert into food(foodName,foodKcal) values ('된장찌개 ',350);
insert into food(foodName,foodKcal) values ('순두부찌개 ',300);
insert into food(foodName,foodKcal) values ('콩나물국밥 ',350);
insert into food(foodName,foodKcal) values ('수제비 ',400);
insert into food(foodName,foodKcal) values ('칼국수 ',400);
insert into food(foodName,foodKcal) values ('라볶이 ',400);
insert into food(foodName,foodKcal) values ('만두국 ',450);
insert into food(foodName,foodKcal) values ('떡국 ',400);
insert into food(foodName,foodKcal) values ('설렁탕 ',550);
insert into food(foodName,foodKcal) values ('추어탕 ',400);
insert into food(foodName,foodKcal) values ('아귀찜 ',350);
insert into food(foodName,foodKcal) values ('게장 ',150);
insert into food(foodName,foodKcal) values ('장어구이 ',300);
insert into food(foodName,foodKcal) values ('곰장어구이 ',200);
insert into food(foodName,foodKcal) values ('새우구이 ',120);
insert into food(foodName,foodKcal) values ('바지락 칼국수 ',400);
insert into food(foodName,foodKcal) values ('잔치국수 ',300);
insert into food(foodName,foodKcal) values ('비빔국수 ',450);
insert into food(foodName,foodKcal) values ('콩국수 ',550);
insert into food(foodName,foodKcal) values ('도토리묵 무침 ',45);
insert into food(foodName,foodKcal) values ('오이소박이 ',30);
insert into food(foodName,foodKcal) values ('깍두기 ',40);
insert into food(foodName,foodKcal) values ('총각김치 ',50);
insert into food(foodName,foodKcal) values ('배추김치 ',32);
insert into food(foodName,foodKcal) values ('열무김치 ',25);
insert into food(foodName,foodKcal) values ('오징어채무침 ',150);
insert into food(foodName,foodKcal) values ('무말랭이 ',200);
insert into food(foodName,foodKcal) values ('시금치나물 ',50);
insert into food(foodName,foodKcal) values ('고사리나물 ',60);
insert into food(foodName,foodKcal) values ('도라지나물 ',40);
insert into food(foodName,foodKcal) values ('연근조림 ',150);
insert into food(foodName,foodKcal) values ('무조림 ',70);
insert into food(foodName,foodKcal) values ('두부조림 ',100);
insert into food(foodName,foodKcal) values ('오이무침 ',50);
insert into food(foodName,foodKcal) values ('도토리묵 ',45);
insert into food(foodName,foodKcal) values ('계란말이 ',154);
insert into food(foodName,foodKcal) values ('계란찜 ',90);
insert into food(foodName,foodKcal) values ('순두부 ',60);
insert into food(foodName,foodKcal) values ('매운두부조림 ',80);
insert into food(foodName,foodKcal) values ('연두부 ',50);
insert into food(foodName,foodKcal) values ('황태국 ',150);
insert into food(foodName,foodKcal) values ('미역국 ',60);
insert into food(foodName,foodKcal) values ('북엇국 ',100);
insert into food(foodName,foodKcal) values ('조개국 ',70);
insert into food(foodName,foodKcal) values ('굴국 ',80);
insert into food(foodName,foodKcal) values ('도가니탕 ',350);
insert into food(foodName,foodKcal) values ('닭곰탕 ',400);
insert into food(foodName,foodKcal) values ('소고기무국 ',150);
insert into food(foodName,foodKcal) values ('육개장 ',200);
insert into food(foodName,foodKcal) values ('들깨미역국 ',120);
insert into food(foodName,foodKcal) values ('북어채볶음 ',100);
insert into food(foodName,foodKcal) values ('멸치볶음 ',200);
insert into food(foodName,foodKcal) values ('진미채볶음 ',150);
insert into food(foodName,foodKcal) values ('새우젓 ',100);
insert into food(foodName,foodKcal) values ('간장게장 ',150);
insert into food(foodName,foodKcal) values ('양념치킨 ',290);
insert into food(foodName,foodKcal) values ('간장치킨 ',270);
insert into food(foodName,foodKcal) values ('닭발 ',215);
insert into food(foodName,foodKcal) values ('골뱅이무침 ',110);
insert into food(foodName,foodKcal) values ('순대볶음 ',200);
insert into food(foodName,foodKcal) values ('치즈떡볶이 ',200);
insert into food(foodName,foodKcal) values ('주꾸미볶음 ',150);
insert into food(foodName,foodKcal) values ('감자탕 ',450);
insert into food(foodName,foodKcal) values ('동태탕 ',200);
insert into food(foodName,foodKcal) values ('고등어구이 ',200);
insert into food(foodName,foodKcal) values ('갈치구이 ',250);
insert into food(foodName,foodKcal) values ('장어덮밥 ',650);
insert into food(foodName,foodKcal) values ('육회 ',190);
insert into food(foodName,foodKcal) values ('한치회 ',80);
insert into food(foodName,foodKcal) values ('홍합탕 ',100);
insert into food(foodName,foodKcal) values ('꽃게탕 ',150);
insert into food(foodName,foodKcal) values ('대구매운탕 ',200);
insert into food(foodName,foodKcal) values ('미더덕찜 ',180);
insert into food(foodName,foodKcal) values ('해물파전 ',400);
insert into food(foodName,foodKcal) values ('감자전 ',300);
insert into food(foodName,foodKcal) values ('김치전 ',250);
insert into food(foodName,foodKcal) values ('고구마전 ',250);
insert into food(foodName,foodKcal) values ('부추전 ',200);
insert into food(foodName,foodKcal) values ('깻잎전 ',150);
insert into food(foodName,foodKcal) values ('두부전 ',180);
insert into food(foodName,foodKcal) values ('감자채볶음 ',120);
insert into food(foodName,foodKcal) values ('콩자반 ',140);
insert into food(foodName,foodKcal) values ('도토리묵 무침 ',50);
insert into food(foodName,foodKcal) values ('가지나물 ',40);
insert into food(foodName,foodKcal) values ('브로콜리 무침 ',35);
insert into food(foodName,foodKcal) values ('연근무침 ',70);
insert into food(foodName,foodKcal) values ('애호박볶음 ',80);
insert into food(foodName,foodKcal) values ('버섯볶음 ',100);
insert into food(foodName,foodKcal) values ('미나리나물 ',30);
insert into food(foodName,foodKcal) values ('양배추쌈 ',25);
insert into food(foodName,foodKcal) values ('파김치 ',45);
insert into food(foodName,foodKcal) values ('갓김치 ',50);
insert into food(foodName,foodKcal) values ('백김치 ',20);
insert into food(foodName,foodKcal) values ('오이피클 ',40);
insert into food(foodName,foodKcal) values ('무피클 ',35);
insert into food(foodName,foodKcal) values ('시금치 된장국 ',60);
insert into food(foodName,foodKcal) values ('참치김치찌개 ',450);
insert into food(foodName,foodKcal) values ('낙지볶음 ',150);
insert into food(foodName,foodKcal) values ('곤드레밥 ',320);
insert into food(foodName,foodKcal) values ('유부초밥 ',70);
insert into food(foodName,foodKcal) values ('김밥 ',320);
insert into food(foodName,foodKcal) values ('삼각김밥 ',180);
insert into food(foodName,foodKcal) values ('참치마요김밥 ',350);
insert into food(foodName,foodKcal) values ('새우김밥 ',300);
insert into food(foodName,foodKcal) values ('불고기김밥 ',400);
insert into food(foodName,foodKcal) values ('야채김밥 ',250);
insert into food(foodName,foodKcal) values ('우엉김밥 ',300);
insert into food(foodName,foodKcal) values ('치즈김밥 ',350);
insert into food(foodName,foodKcal) values ('멸치김밥 ',350);
insert into food(foodName,foodKcal) values ('해물짬뽕 ',600);
insert into food(foodName,foodKcal) values ('짜장면 ',700);
insert into food(foodName,foodKcal) values ('울면 ',550);
insert into food(foodName,foodKcal) values ('탕수육 ',250);
insert into food(foodName,foodKcal) values ('군만두 ',50);
insert into food(foodName,foodKcal) values ('물만두 ',35);
insert into food(foodName,foodKcal) values ('양장피 ',400);
insert into food(foodName,foodKcal) values ('깐풍기 ',320);
insert into food(foodName,foodKcal) values ('라조기 ',350);
insert into food(foodName,foodKcal) values ('팔보채 ',200);
insert into food(foodName,foodKcal) values ('칠리새우 ',280);
insert into food(foodName,foodKcal) values ('고추잡채 ',220);
insert into food(foodName,foodKcal) values ('유산슬 ',200);
insert into food(foodName,foodKcal) values ('북경오리 ',340);
insert into food(foodName,foodKcal) values ('동파육 ',400);
insert into food(foodName,foodKcal) values ('게살볶음밥 ',550);
insert into food(foodName,foodKcal) values ('새우볶음밥 ',500);
insert into food(foodName,foodKcal) values ('쇠고기볶음밥 ',600);
insert into food(foodName,foodKcal) values ('야채볶음밥 ',450);
insert into food(foodName,foodKcal) values ('게살 스프 ',150);
insert into food(foodName,foodKcal) values ('완탕 ',200);
insert into food(foodName,foodKcal) values ('양탕 ',250);
insert into food(foodName,foodKcal) values ('샤오롱바오 ',60);
insert into food(foodName,foodKcal) values ('새우 딤섬 ',50);
insert into food(foodName,foodKcal) values ('찐빵 ',150);
insert into food(foodName,foodKcal) values ('단팥빵 ',200);
insert into food(foodName,foodKcal) values ('야채빵 ',250);
insert into food(foodName,foodKcal) values ('커스터드 크림빵 ',280);
insert into food(foodName,foodKcal) values ('소보로빵 ',300);
insert into food(foodName,foodKcal) values ('바게트 ',270);
insert into food(foodName,foodKcal) values ('치아바타 ',250);
insert into food(foodName,foodKcal) values ('크루아상 ',230);
insert into food(foodName,foodKcal) values ('데니쉬 페이스트리 ',400);
insert into food(foodName,foodKcal) values ('머핀 ',400);
insert into food(foodName,foodKcal) values ('스콘 ',300);
insert into food(foodName,foodKcal) values ('브리오슈 ',330);
insert into food(foodName,foodKcal) values ('피자 ',250-400);
insert into food(foodName,foodKcal) values ('마르게리타 피자 ',270);
insert into food(foodName,foodKcal) values ('페퍼로니 피자 ',300);
insert into food(foodName,foodKcal) values ('콤비네이션 피자 ',350);
insert into food(foodName,foodKcal) values ('치즈 피자 ',290);
insert into food(foodName,foodKcal) values ('하와이안 피자 ',320);
insert into food(foodName,foodKcal) values ('불고기 피자 ',340);
insert into food(foodName,foodKcal) values ('바베큐 치킨 피자 ',380);
insert into food(foodName,foodKcal) values ('멕시칸 피자 ',360);
insert into food(foodName,foodKcal) values ('베지 피자 ',250);
insert into food(foodName,foodKcal) values ('파스타 ',350);
insert into food(foodName,foodKcal) values ('스파게티 볼로네즈 ',600);
insert into food(foodName,foodKcal) values ('알프레도 파스타 ',800);
insert into food(foodName,foodKcal) values ('까르보나라 ',750);
insert into food(foodName,foodKcal) values ('라자냐 ',600);
insert into food(foodName,foodKcal) values ('페스토 파스타 ',400);
insert into food(foodName,foodKcal) values ('마카로니 앤 치즈 ',450);
insert into food(foodName,foodKcal) values ('샐러드 ',150);
insert into food(foodName,foodKcal) values ('시저 샐러드 ',300);
insert into food(foodName,foodKcal) values ('그린 샐러드 ',100);
insert into food(foodName,foodKcal) values ('치킨 샐러드 ',350);
insert into food(foodName,foodKcal) values ('감자튀김 ',300);
insert into food(foodName,foodKcal) values ('치즈버거 ',500);
insert into food(foodName,foodKcal) values ('핫도그 ',400);
insert into food(foodName,foodKcal) values ('클럽 샌드위치 ',600);
insert into food(foodName,foodKcal) values ('터키 샌드위치 ',350);
insert into food(foodName,foodKcal) values ('BLT 샌드위치 ',400);
insert into food(foodName,foodKcal) values ('햄 샌드위치 ',300);
insert into food(foodName,foodKcal) values ('스테이크 ',250);
insert into food(foodName,foodKcal) values ('립아이 스테이크 ',300);
insert into food(foodName,foodKcal) values ('티본 스테이크 ',350);
insert into food(foodName,foodKcal) values ('연어 스테이크 ',200);
insert into food(foodName,foodKcal) values ('치킨 스테이크 ',150);
insert into food(foodName,foodKcal) values ('치킨 커틀릿 ',350);
insert into food(foodName,foodKcal) values ('돈가스 ',400);
insert into food(foodName,foodKcal) values ('필라프 ',600);
insert into food(foodName,foodKcal) values ('리소토 ',500);
insert into food(foodName,foodKcal) values ('바베큐 립 ',300);
insert into food(foodName,foodKcal) values ('바비큐 치킨 ',250);
insert into food(foodName,foodKcal) values ('칠리 콘 카르네 ',400);
insert into food(foodName,foodKcal) values ('나초 ',350);
insert into food(foodName,foodKcal) values ('타코 ',200);
insert into food(foodName,foodKcal) values ('부리토 ',500);
insert into food(foodName,foodKcal) values ('파히타 ',450);
insert into food(foodName,foodKcal) values ('큐브라이스 ',600);
insert into food(foodName,foodKcal) values ('치즈 케이크 ',350);
insert into food(foodName,foodKcal) values ('초콜릿 케이크 ',400);
insert into food(foodName,foodKcal) values ('당근 케이크 ',350);
insert into food(foodName,foodKcal) values ('티라미수 ',450);
insert into food(foodName,foodKcal) values ('애플파이 ',300);
insert into food(foodName,foodKcal) values ('브라우니 ',250);
insert into food(foodName,foodKcal) values ('팬케이크 ',150);
insert into food(foodName,foodKcal) values ('와플 ',200);
insert into food(foodName,foodKcal) values ('크레페 ',150);
insert into food(foodName,foodKcal) values ('도넛 ',250);
insert into food(foodName,foodKcal) values ('마카롱 ',80);
insert into food(foodName,foodKcal) values ('쿠키 ',100);
insert into food(foodName,foodKcal) values ('바나나 스플릿 ',500);
insert into food(foodName,foodKcal) values ('아이스크림 ',200);
insert into food(foodName,foodKcal) values ('젤라또 ',150);
insert into food(foodName,foodKcal) values ('샤베트 ',100);
insert into food(foodName,foodKcal) values ('푸딩 ',130);
insert into food(foodName,foodKcal) values ('플랑 ',150);
insert into food(foodName,foodKcal) values ('판나코타 ',200);
insert into food(foodName,foodKcal) values ('뮤즐리 ',350);
insert into food(foodName,foodKcal) values ('그래놀라 ',400);
insert into food(foodName,foodKcal) values ('요거트 ',60);
insert into food(foodName,foodKcal) values ('요거트 파르페 ',300);
insert into food(foodName,foodKcal) values ('프렌치 토스트 ',250);
insert into food(foodName,foodKcal) values ('오믈렛 ',200);
insert into food(foodName,foodKcal) values ('에그 베네딕트 ',300);
insert into food(foodName,foodKcal) values ('스크램블 에그 ',150);
insert into food(foodName,foodKcal) values ('베이컨 ',540);
insert into food(foodName,foodKcal) values ('소시지 ',300);
insert into food(foodName,foodKcal) values ('퀴노아 샐러드 ',250);
insert into food(foodName,foodKcal) values ('팔라펠 ',330);
insert into food(foodName,foodKcal) values ('후무스 ',166);
insert into food(foodName,foodKcal) values ('바바가누쉬 ',150);
insert into food(foodName,foodKcal) values ('타불리 ',120);
insert into food(foodName,foodKcal) values ('케밥 ',250);
insert into food(foodName,foodKcal) values ('쇼와르마 ',350);
insert into food(foodName,foodKcal) values ('바클라바 ',150);
insert into food(foodName,foodKcal) values ('루쿠마드 ',250);
insert into food(foodName,foodKcal) values ('포케 ',400);
insert into food(foodName,foodKcal) values ('에그 타르트 ',230);
insert into food(foodName,foodKcal) values ('포르투갈식 에그 타르트 ',250);
insert into food(foodName,foodKcal) values ('스페인식 오믈렛 ',200);
insert into food(foodName,foodKcal) values ('파에야 ',500);
insert into food(foodName,foodKcal) values ('가스파초 ',150);
insert into food(foodName,foodKcal) values ('차조기 샐러드 ',100);
insert into food(foodName,foodKcal) values ('문어 샐러드 ',200);
insert into food(foodName,foodKcal) values ('안티파스토 ',300);
insert into food(foodName,foodKcal) values ('크로스티니 ',70);
insert into food(foodName,foodKcal) values ('브루스케타 ',120);
insert into food(foodName,foodKcal) values ('폴렌타 ',70);
insert into food(foodName,foodKcal) values ('라비올리 ',300);
insert into food(foodName,foodKcal) values ('닭고기 파르미지아나 ',600);
insert into food(foodName,foodKcal) values ('미트볼 ',250);
insert into food(foodName,foodKcal) values ('리코타 치즈 ',174);
insert into food(foodName,foodKcal) values ('아란치니 ',150);
insert into food(foodName,foodKcal) values ('카놀리 ',200);
insert into food(foodName,foodKcal) values ('티본 스테이크 ',350);
insert into food(foodName,foodKcal) values ('마르게리타 피자 ',270);
insert into food(foodName,foodKcal) values ('프로슈토 ',210);
insert into food(foodName,foodKcal) values ('모짜렐라 치즈 ',280);
insert into food(foodName,foodKcal) values ('트러플 오일 ',120);
insert into food(foodName,foodKcal) values ('에스카르고 ',90);
insert into food(foodName,foodKcal) values ('뵈프 부르기뇽 ',400);
insert into food(foodName,foodKcal) values ('라따뚜이 ',180);
insert into food(foodName,foodKcal) values ('퀴슈 ',300);
insert into food(foodName,foodKcal) values ('비빔밥 ',600);
insert into food(foodName,foodKcal) values ('불고기 ',270);
insert into food(foodName,foodKcal) values ('갈비찜 ',350);
insert into food(foodName,foodKcal) values ('떡국 ',350);
insert into food(foodName,foodKcal) values ('김밥 ',320);
insert into food(foodName,foodKcal) values ('물냉면 ',400);
insert into food(foodName,foodKcal) values ('비빔냉면 ',500);
insert into food(foodName,foodKcal) values ('감자탕 ',450);
insert into food(foodName,foodKcal) values ('순대국 ',450);
insert into food(foodName,foodKcal) values ('족발 ',250);
insert into food(foodName,foodKcal) values ('보쌈 ',300);
insert into food(foodName,foodKcal) values ('닭갈비 ',230);
insert into food(foodName,foodKcal) values ('제육볶음 ',280);
insert into food(foodName,foodKcal) values ('된장찌개 ',200);
insert into food(foodName,foodKcal) values ('김치찌개 ',250);
insert into food(foodName,foodKcal) values ('순두부찌개 ',300);
insert into food(foodName,foodKcal) values ('청국장 ',250);
insert into food(foodName,foodKcal) values ('잡채 ',150);
insert into food(foodName,foodKcal) values ('갈비탕 ',350);
insert into food(foodName,foodKcal) values ('육개장 ',300);
insert into food(foodName,foodKcal) values ('설렁탕 ',400);
insert into food(foodName,foodKcal) values ('곰탕 ',350);
insert into food(foodName,foodKcal) values ('감자전 ',300);
insert into food(foodName,foodKcal) values ('해물파전 ',400);
insert into food(foodName,foodKcal) values ('빈대떡 ',350);
insert into food(foodName,foodKcal) values ('김치전 ',250);
insert into food(foodName,foodKcal) values ('고구마전 ',250);
insert into food(foodName,foodKcal) values ('두부전 ',180);
insert into food(foodName,foodKcal) values ('호박죽 ',250);
insert into food(foodName,foodKcal) values ('팥죽 ',350);
insert into food(foodName,foodKcal) values ('콩나물국 ',100);
insert into food(foodName,foodKcal) values ('미역국 ',100);
insert into food(foodName,foodKcal) values ('북엇국 ',120);
insert into food(foodName,foodKcal) values ('떡꼬치 ',200);
insert into food(foodName,foodKcal) values ('달고나 ',50);
insert into food(foodName,foodKcal) values ('팥빙수 ',350);
insert into food(foodName,foodKcal) values ('인절미 ',200);
insert into food(foodName,foodKcal) values ('송편 ',60);
insert into food(foodName,foodKcal) values ('약과 ',150);
insert into food(foodName,foodKcal) values ('유과 ',400);
insert into food(foodName,foodKcal) values ('호두과자 ',50);
insert into food(foodName,foodKcal) values ('찹쌀떡 ',100);
insert into food(foodName,foodKcal) values ('바나나 ',90);
insert into food(foodName,foodKcal) values ('사과 ',50);
insert into food(foodName,foodKcal) values ('포도 ',70);
insert into food(foodName,foodKcal) values ('수박 ',30);
insert into food(foodName,foodKcal) values ('오렌지 ',45);
insert into food(foodName,foodKcal) values ('딸기 ',32);
insert into food(foodName,foodKcal) values ('블루베리 ',57);
insert into food(foodName,foodKcal) values ('자두 ',46);
insert into food(foodName,foodKcal) values ('복숭아 ',39);
insert into food(foodName,foodKcal) values ('망고 ',60);
insert into food(foodName,foodKcal) values ('파인애플 ',50);
insert into food(foodName,foodKcal) values ('키위 ',41);
insert into food(foodName,foodKcal) values ('자몽 ',32);
insert into food(foodName,foodKcal) values ('체리 ',63);
insert into food(foodName,foodKcal) values ('레몬 ',29);
insert into food(foodName,foodKcal) values ('라임 ',30);
insert into food(foodName,foodKcal) values ('감 ',70);
insert into food(foodName,foodKcal) values ('무화과 ',74);
insert into food(foodName,foodKcal) values ('코코넛 ',354);
insert into food(foodName,foodKcal) values ('아보카도 ',160);
insert into food(foodName,foodKcal) values ('피스타치오 ',560);
insert into food(foodName,foodKcal) values ('아몬드 ',580);
insert into food(foodName,foodKcal) values ('캐슈넛 ',550);
insert into food(foodName,foodKcal) values ('호두 ',654);
insert into food(foodName,foodKcal) values ('땅콩 ',567);
insert into food(foodName,foodKcal) values ('해바라기씨 ',584);
insert into food(foodName,foodKcal) values ('치아씨드 ',486);
insert into food(foodName,foodKcal) values ('퀴노아 ',368);
insert into food(foodName,foodKcal) values ('현미 ',110);
insert into food(foodName,foodKcal) values ('흰쌀밥 ',130);
insert into food(foodName,foodKcal) values ('현미밥 ',112);
insert into food(foodName,foodKcal) values ('잡곡밥 ',120);
insert into food(foodName,foodKcal) values ('보리밥 ',110);
insert into food(foodName,foodKcal) values ('수수밥 ',120);
insert into food(foodName,foodKcal) values ('찹쌀밥 ',130);
insert into food(foodName,foodKcal) values ('기장밥 ',110);
insert into food(foodName,foodKcal) values ('강정 ',100);
insert into food(foodName,foodKcal) values ('식혜 ',150);
insert into food(foodName,foodKcal) values ('수정과 ',120);
insert into food(foodName,foodKcal) values ('율무차 ',130);
insert into food(foodName,foodKcal) values ('대추차 ',140);
insert into food(foodName,foodKcal) values ('매실차 ',80);
insert into food(foodName,foodKcal) values ('오미자차 ',60);
insert into food(foodName,foodKcal) values ('생강차 ',100);
insert into food(foodName,foodKcal) values ('쌍화차 ',90);
insert into food(foodName,foodKcal) values ('칡차 ',70);
insert into food(foodName,foodKcal) values ('둥굴레차 ',30);
insert into food(foodName,foodKcal) values ('국화차 ',20);
insert into food(foodName,foodKcal) values ('보리차 ',5);
insert into food(foodName,foodKcal) values ('옥수수수염차 ',0);
insert into food(foodName,foodKcal) values ('맥콜 ',150);
insert into food(foodName,foodKcal) values ('비락식혜 ',150);
insert into food(foodName,foodKcal) values ('초코파이 ',120);
insert into food(foodName,foodKcal) values ('새우깡 ',480);
insert into food(foodName,foodKcal) values ('감자칩 ',550);
insert into food(foodName,foodKcal) values ('포카칩 ',540);
insert into food(foodName,foodKcal) values ('양파링 ',500);
insert into food(foodName,foodKcal) values ('고구마칩 ',500);
insert into food(foodName,foodKcal) values ('퀘사디아 ',500);
insert into food(foodName,foodKcal) values ('엔칠라다 ',300);
insert into food(foodName,foodKcal) values ('타말레 ',250);
insert into food(foodName,foodKcal) values ('에그롤 ',200);
insert into food(foodName,foodKcal) values ('봄롤 ',150);
insert into food(foodName,foodKcal) values ('훈제 연어 ',170);
insert into food(foodName,foodKcal) values ('초밥 ',50);
insert into food(foodName,foodKcal) values ('사시미 ',150);
insert into food(foodName,foodKcal) values ('튀김 우동 ',450);
insert into food(foodName,foodKcal) values ('돈부리 ',500);
insert into food(foodName,foodKcal) values ('규동 ',600);
insert into food(foodName,foodKcal) values ('오코노미야키 ',500);
insert into food(foodName,foodKcal) values ('타코야키 ',60);
insert into food(foodName,foodKcal) values ('텐동 ',600);
insert into food(foodName,foodKcal) values ('야키소바 ',400);
insert into food(foodName,foodKcal) values ('라멘 ',500);
insert into food(foodName,foodKcal) values ('미소 라멘 ',550);
insert into food(foodName,foodKcal) values ('쇼유 라멘 ',500);
insert into food(foodName,foodKcal) values ('탄탄멘 ',600);
insert into food(foodName,foodKcal) values ('츠케멘 ',600);
insert into food(foodName,foodKcal) values ('우동 ',400);
insert into food(foodName,foodKcal) values ('자루소바 ',350);
insert into food(foodName,foodKcal) values ('카츠동 ',700);
insert into food(foodName,foodKcal) values ('우나기동 ',650);
insert into food(foodName,foodKcal) values ('하야시라이스 ',600);
insert into food(foodName,foodKcal) values ('하이라이스 ',600);
insert into food(foodName,foodKcal) values ('카레라이스 ',600);
insert into food(foodName,foodKcal) values ('나폴리탄 ',600);
insert into food(foodName,foodKcal) values ('야키토리 ',100);
insert into food(foodName,foodKcal) values ('타코 ',200);
insert into food(foodName,foodKcal) values ('가츠샌드 ',400);
insert into food(foodName,foodKcal) values ('메밀국수 ',300);
insert into food(foodName,foodKcal) values ('냉모밀 ',350);
insert into food(foodName,foodKcal) values ('파르페 ',350);
insert into food(foodName,foodKcal) values ('푸딩 ',150);
insert into food(foodName,foodKcal) values ('젤리 ',100);
insert into food(foodName,foodKcal) values ('크렘 브륄레 ',250);
insert into food(foodName,foodKcal) values ('몬스터 에너지 드링크 ',210);
insert into food(foodName,foodKcal) values ('레드불 ',110);
insert into food(foodName,foodKcal) values ('초코칩 쿠키 ',50);
insert into food(foodName,foodKcal) values ('아몬드 쿠키 ',70);
insert into food(foodName,foodKcal) values ('땅콩버터 쿠키 ',80);
insert into food(foodName,foodKcal) values ('오트밀 쿠키 ',60);
insert into food(foodName,foodKcal) values ('레몬머랭파이 ',250);
insert into food(foodName,foodKcal) values ('코코넛파이 ',350);
insert into food(foodName,foodKcal) values ('블루베리파이 ',300);
insert into food(foodName,foodKcal) values ('피칸파이 ',450);
insert into food(foodName,foodKcal) values ('딸기파이 ',300);
insert into food(foodName,foodKcal) values ('아이스크림 케이크 ',300);
insert into food(foodName,foodKcal) values ('피나콜라다 ',200);
insert into food(foodName,foodKcal) values ('마가리타 ',150);
insert into food(foodName,foodKcal) values ('모히토 ',150);
insert into food(foodName,foodKcal) values ('다이키리 ',150);
insert into food(foodName,foodKcal) values ('싱가포르 슬링 ',200);
insert into food(foodName,foodKcal) values ('럼펀치 ',200);
insert into food(foodName,foodKcal) values ('블러디 메리 ',120);
insert into food(foodName,foodKcal) values ('피치 아이스티 ',160);
insert into food(foodName,foodKcal) values ('롱 아일랜드 아이스티 ',250);
insert into food(foodName,foodKcal) values ('코스모폴리탄 ',150);
insert into food(foodName,foodKcal) values ('맥주 ',150);
insert into food(foodName,foodKcal) values ('사과주 ',200);
insert into food(foodName,foodKcal) values ('와인 ',120);
insert into food(foodName,foodKcal) values ('샴페인 ',90);
insert into food(foodName,foodKcal) values ('보드카 ',100);
insert into food(foodName,foodKcal) values ('위스키 ',100);
insert into food(foodName,foodKcal) values ('럼 ',100);
insert into food(foodName,foodKcal) values ('데킬라 ',100);
insert into food(foodName,foodKcal) values ('진 ',100);
insert into food(foodName,foodKcal) values ('코냑 ',100);
insert into food(foodName,foodKcal) values ('리큐르 ',150);
insert into food(foodName,foodKcal) values ('핫초콜릿 ',200);
insert into food(foodName,foodKcal) values ('라떼 ',190);
insert into food(foodName,foodKcal) values ('카푸치노 ',150);
insert into food(foodName,foodKcal) values ('에스프레소 ',30);
insert into food(foodName,foodKcal) values ('아메리카노 ',15);
insert into food(foodName,foodKcal) values ('카라멜 마끼아또 ',250);
insert into food(foodName,foodKcal) values ('프라푸치노 ',300);
insert into food(foodName,foodKcal) values ('그린티 라떼 ',200);
insert into food(foodName,foodKcal) values ('모카 라떼 ',250);
insert into food(foodName,foodKcal) values ('밀크티 ',180);
insert into food(foodName,foodKcal) values ('버블티 ',250);
insert into food(foodName,foodKcal) values ('차이티 ',150);
insert into food(foodName,foodKcal) values ('얼그레이 티 ',0);
insert into food(foodName,foodKcal) values ('페퍼민트 티 ',0);
insert into food(foodName,foodKcal) values ('카모마일 티 ',0);
insert into food(foodName,foodKcal) values ('자스민 티 ',0);
insert into food(foodName,foodKcal) values ('녹차 ',0);
insert into food(foodName,foodKcal) values ('홍차 ',0);
insert into food(foodName,foodKcal) values ('아이스티 ',90);
insert into food(foodName,foodKcal) values ('레몬에이드 ',120);
insert into food(foodName,foodKcal) values ('오렌지 주스 ',110);
insert into food(foodName,foodKcal) values ('사과 주스 ',120);
insert into food(foodName,foodKcal) values ('포도 주스 ',150);
insert into food(foodName,foodKcal) values ('토마토 주스 ',50);
insert into food(foodName,foodKcal) values ('망고 주스 ',130);
insert into food(foodName,foodKcal) values ('파인애플 주스 ',130);
insert into food(foodName,foodKcal) values ('석류 주스 ',150);
insert into food(foodName,foodKcal) values ('키위 주스 ',120);
insert into food(foodName,foodKcal) values ('당근 주스 ',90);
insert into food(foodName,foodKcal) values ('코코넛 워터 ',45);


select * from food;
select * from member;
select * from atefoodrecord;
select * from food inner join atefoodrecord on food.foodcode=atefoodrecord.foodcode;

select foodCode from member inner join atefoodrecord on member.memberCode = atefoodrecord.memberCode where member.memberCode = 2;

select foodKcal from food where foodCode = 1;


